# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  merge_group:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Bump version
      if: ${{ github.event_name == 'merge_request' }}
      run: mvn validate -DbumpPatch
    - name: Commit changes
      if: ${{ github.event_name == 'merge_request' }}
      run: |
        git config --global user.name 'Rakesh Jose Thomas'
        git config --global user.email 'rakesh.thomas@apicasystems.com'
        git config pull.rebase false
        git add pom.xml
        git commit -m "Bumps version"
        git pull origin ${{ github.head_ref }} --allow-unrelated-histories
        git push origin ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
